### ISSUE TITLE
想詢問是否能夠加入協作

### ISSUE THREAD

**Issue by Latisha19** [nikkitw/nikkitw#3]
您好：
不好意思打擾了，我是受惠於您們所做的奇蹟暖暖搭配器的人之一，最近意外翻到搭配器的原始碼，發現協作者似乎只有一位，想說不知是否能夠加入協作呢？純粹做 pull request 的。
主因是最近發現搭配器回報者眾多，但處理者只有一位，猜想是否有點負擔的可能...因此傳訊息做個詢問，畢竟作為受惠者，還是稍微希望能做點分攤的。
預先感謝您的閱覽與回覆。

**Comment by nikkitw** [comment]
您好，
感謝您留言，剛好這幾個月稍微忙一些，搭配器的更新嚴重落後，目前是六月就不忙了，會回歸正常更新。
如果願意的話可以先聯繫我的mail：jojo001537@gmail.com，我再邀請您加入LINE的社團群組，可以討論一下之後搭配器如何更新。
謝謝。

**Comment by Latisha19** [comment]
> 您好，
> 感謝您留言，剛好這幾個月稍微忙一些，搭配器的更新嚴重落後，目前是六月就不忙了，會回歸正常更新。
> 如果願意的話可以先聯繫我的mail：jojo001537@gmail.com，我再邀請您加入LINE的社團群組，可以討論一下之後搭配器如何更新。
> 謝謝。

好的，那麼我晚點會聯繫您的mail，非常感謝您願意讓我加入協作！

也請您保重身體，身體比較重要。
